/**
 * Gemini API Client
 * Uses Gemini 2.0 Flash (free tier) for all agent interactions
 */

const GEMINI_API_URL = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent';

/**
 * Fetch helper that handles automatic retries with exponential backoff on 429 errors.
 */
async function fetchWithRetry(url, options, maxRetries = 5, baseDelayMs = 2000) {
  let attempt = 0;
  while (true) {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 15000); // 15s timeout
    
    try {
      const response = await fetch(url, {
        ...options,
        signal: controller.signal
      });
      clearTimeout(timeoutId);

      if (response.status === 429) {
        attempt++;
        let isDailyLimit = false;
        let delay = baseDelayMs * Math.pow(2, attempt - 1) + Math.random() * 500;

        try {
          const errText = await response.text(); // Safe because we discard this response
          const errObj = JSON.parse(errText);
          
          // Check if this is a hard daily quota limit
          if (errText.includes('GenerateRequestsPerDay') || errText.includes('PerDay')) {
            isDailyLimit = true;
          }

          const details = errObj?.error?.details;
          if (Array.isArray(details)) {
            const retryInfo = details.find(d => d && d.retryDelay);
            if (retryInfo && retryInfo.retryDelay) {
              const seconds = parseInt(retryInfo.retryDelay);
              if (!isNaN(seconds)) {
                delay = (seconds + 1.5) * 1000;
              }
            }
          }
        } catch (e) {
          // Fall back to exponential backoff
        }

        if (isDailyLimit) {
          console.error('[Gemini API 429] Daily quota exceeded. Aborting further attempts.');
          return response;
        }

        if (attempt > maxRetries) {
          return response;
        }

        console.warn(`[Gemini API 429] Rate limit hit. Retrying in ${Math.round(delay)}ms... (Attempt ${attempt}/${maxRetries})`);
        await new Promise(resolve => setTimeout(resolve, delay));
        continue;
      }
      return response;
    } catch (error) {
      clearTimeout(timeoutId);
      attempt++;
      if (attempt > maxRetries) {
        throw error;
      }
      const delay = baseDelayMs * Math.pow(2, attempt - 1) + Math.random() * 500;
      const isTimeout = error.name === 'AbortError';
      console.warn(`[Fetch Error] ${isTimeout ? 'Request timed out after 15s' : error.message}. Retrying in ${Math.round(delay)}ms... (Attempt ${attempt}/${maxRetries})`);
      await new Promise(resolve => setTimeout(resolve, delay));
    }
  }
}

/**
 * Call Gemini API with a prompt and return the text response (Internal helper)
 */
async function callProviderGemini(prompt, apiKey) {
  const response = await fetchWithRetry(`${GEMINI_API_URL}?key=${apiKey}`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      contents: [
        {
          parts: [
            {
              text: prompt
            }
          ]
        }
      ],
      generationConfig: {
        temperature: 0.9,
        topP: 0.95,
        topK: 40,
        maxOutputTokens: 1024,
      },
      safetySettings: [
        {
          category: 'HARM_CATEGORY_HARASSMENT',
          threshold: 'BLOCK_ONLY_HIGH'
        },
        {
          category: 'HARM_CATEGORY_HATE_SPEECH',
          threshold: 'BLOCK_ONLY_HIGH'
        },
        {
          category: 'HARM_CATEGORY_SEXUALLY_EXPLICIT',
          threshold: 'BLOCK_ONLY_HIGH'
        },
        {
          category: 'HARM_CATEGORY_DANGEROUS_CONTENT',
          threshold: 'BLOCK_ONLY_HIGH'
        }
      ]
    })
  });

  if (!response.ok) {
    const errorBody = await response.text();
    throw new Error(`Gemini API error: ${response.status} — ${errorBody}`);
  }

  const data = await response.json();

  if (!data.candidates || data.candidates.length === 0) {
    throw new Error('No response generated by Gemini');
  }

  const candidate = data.candidates[0];

  if (candidate.finishReason === 'SAFETY') {
    throw new Error('Response blocked by safety filters');
  }

  return candidate.content?.parts?.[0]?.text || '';
}

/**
 * Call OpenAI-compatible API (Internal helper)
 */
async function callProviderOpenAI(url, apiKey, model, prompt) {
  const response = await fetchWithRetry(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${apiKey}`,
      'HTTP-Referer': 'https://cascade-validator.vercel.app',
      'X-Title': 'Cascade'
    },
    body: JSON.stringify({
      model: model,
      messages: [
        {
          role: 'user',
          content: prompt
        }
      ],
      temperature: 0.7,
      max_tokens: 1024
    })
  });

  if (!response.ok) {
    const errorBody = await response.text();
    throw new Error(`OpenAI-compatible error (${model}): ${response.status} — ${errorBody}`);
  }

  const data = await response.json();
  return data.choices?.[0]?.message?.content || '';
}

/**
 * Public function to call an AI with prompt, supporting automatic fallbacks
 */
export async function callGemini(prompt, apiKey) {
  // Try Gemini first
  try {
    if (!apiKey) {
      throw new Error('Gemini API key is missing');
    }
    return await callProviderGemini(prompt, apiKey);
  } catch (geminiError) {
    console.warn(`[Fallback] callGemini failed: ${geminiError.message}. Trying Groq...`);
  }

  // Fallback 1: Groq
  const groqKey = process.env.GROQ_API_KEY;
  try {
    if (!groqKey) {
      throw new Error('Groq API key is missing');
    }
    return await callProviderOpenAI(
      'https://api.groq.com/openai/v1/chat/completions',
      groqKey,
      'llama-3.3-70b-versatile',
      prompt
    );
  } catch (groqError) {
    console.warn(`[Fallback] callGemini failed: ${groqError.message}. Trying OpenRouter...`);
  }

  // Fallback 2: OpenRouter
  const openrouterKey = process.env.OPENROUTER_API_KEY;
  try {
    if (!openrouterKey) {
      throw new Error('OpenRouter API key is missing');
    }
    return await callProviderOpenAI(
      'https://openrouter.ai/api/v1/chat/completions',
      openrouterKey,
      'meta-llama/llama-3-8b-instruct:free',
      prompt
    );
  } catch (orError) {
    console.error(`[Fallback] All callGemini providers failed.`);
    throw new Error('All AI providers failed. Gemini, Groq, and OpenRouter are unavailable.');
  }
}

/**
 * Call Gemini with streaming (Internal helper)
 */
async function* streamProviderGemini(prompt, apiKey) {
  const STREAM_URL = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:streamGenerateContent';
  
  const response = await fetchWithRetry(`${STREAM_URL}?key=${apiKey}&alt=sse`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      contents: [
        {
          parts: [
            {
              text: prompt
            }
          ]
        }
      ],
      generationConfig: {
        temperature: 0.9,
        topP: 0.95,
        topK: 40,
        maxOutputTokens: 1024,
      },
      safetySettings: [
        {
          category: 'HARM_CATEGORY_HARASSMENT',
          threshold: 'BLOCK_ONLY_HIGH'
        },
        {
          category: 'HARM_CATEGORY_HATE_SPEECH',
          threshold: 'BLOCK_ONLY_HIGH'
        },
        {
          category: 'HARM_CATEGORY_SEXUALLY_EXPLICIT',
          threshold: 'BLOCK_ONLY_HIGH'
        },
        {
          category: 'HARM_CATEGORY_DANGEROUS_CONTENT',
          threshold: 'BLOCK_ONLY_HIGH'
        }
      ]
    })
  });

  if (!response.ok) {
    const errorBody = await response.text();
    throw new Error(`Gemini streaming error: ${response.status} — ${errorBody}`);
  }

  const reader = response.body.getReader();
  const decoder = new TextDecoder();
  let buffer = '';

  while (true) {
    const { done, value } = await reader.read();
    if (done) break;

    buffer += decoder.decode(value, { stream: true });
    const lines = buffer.split('\n');
    buffer = lines.pop() || '';

    for (const line of lines) {
      if (line.startsWith('data: ')) {
        const jsonStr = line.slice(6).trim();
        if (jsonStr === '[DONE]') return;
        
        try {
          const data = JSON.parse(jsonStr);
          const text = data.candidates?.[0]?.content?.parts?.[0]?.text;
          if (text) {
            yield text;
          }
        } catch (e) {
          // Skip malformed JSON chunks
        }
      }
    }
  }
}

/**
 * Call OpenAI-compatible API with streaming (Internal helper)
 */
async function* streamProviderOpenAI(url, apiKey, model, prompt) {
  const response = await fetchWithRetry(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${apiKey}`,
      'HTTP-Referer': 'https://cascade-validator.vercel.app',
      'X-Title': 'Cascade'
    },
    body: JSON.stringify({
      model: model,
      messages: [
        {
          role: 'user',
          content: prompt
        }
      ],
      stream: true,
      temperature: 0.7,
      max_tokens: 1024
    })
  });

  if (!response.ok) {
    const errorBody = await response.text();
    throw new Error(`OpenAI-compatible stream error (${model}): ${response.status} — ${errorBody}`);
  }

  const reader = response.body.getReader();
  const decoder = new TextDecoder();
  let buffer = '';

  while (true) {
    const { done, value } = await reader.read();
    if (done) break;

    buffer += decoder.decode(value, { stream: true });
    const lines = buffer.split('\n');
    buffer = lines.pop() || '';

    for (const line of lines) {
      const cleanLine = line.trim();
      if (!cleanLine) continue;

      if (cleanLine.startsWith('data: ')) {
        const jsonStr = cleanLine.slice(6).trim();
        if (jsonStr === '[DONE]') return;
        
        try {
          const data = JSON.parse(jsonStr);
          const text = data.choices?.[0]?.delta?.content;
          if (text) {
            yield text;
          }
        } catch (e) {
          // Skip malformed JSON chunks
        }
      }
    }
  }
}

/**
 * Call Gemini with streaming, supporting automatic fallbacks
 * Yields text chunks as they arrive
 */
export async function* streamGemini(prompt, apiKey) {
  // Try Gemini first
  try {
    if (!apiKey) {
      throw new Error('Gemini API key is missing');
    }
    yield* streamProviderGemini(prompt, apiKey);
    return;
  } catch (geminiError) {
    console.warn(`[Fallback] Gemini streaming failed: ${geminiError.message}. Trying Groq...`);
  }

  // Fallback 1: Groq
  const groqKey = process.env.GROQ_API_KEY;
  try {
    if (!groqKey) {
      throw new Error('Groq API key is missing');
    }
    yield* streamProviderOpenAI(
      'https://api.groq.com/openai/v1/chat/completions',
      groqKey,
      'llama-3.3-70b-versatile',
      prompt
    );
    return;
  } catch (groqError) {
    console.warn(`[Fallback] Groq streaming failed: ${groqError.message}. Trying OpenRouter...`);
  }

  // Fallback 2: OpenRouter
  const openrouterKey = process.env.OPENROUTER_API_KEY;
  try {
    if (!openrouterKey) {
      throw new Error('OpenRouter API key is missing');
    }
    yield* streamProviderOpenAI(
      'https://openrouter.ai/api/v1/chat/completions',
      openrouterKey,
      'meta-llama/llama-3-8b-instruct:free',
      prompt
    );
    return;
  } catch (orError) {
    console.error(`[Fallback] All streaming providers failed. OpenRouter error: ${orError.message}`);
    throw new Error('All AI providers failed. Gemini, Groq, and OpenRouter are unavailable.');
  }
}
